### ISSUE TITLE
Creating script for setting up backend service in local for testing

### ISSUE THREAD

**Issue by neon-lab-dev** [neon-lab-dev/login-service#15]
## Problem
As the AWS in free tire has limited space. We are planning for testing purpose we will provide the setup in the local of the frontend developer

Linked to #4 

cc- @smackdowna @PremanandChowdhury

**Comment by neon-lab-dev** [comment]
# Steps to follow for local setup of the login service in local

- Download Docker and Docker compose in you local system.
- And use the docker-compose file to do the setup. file 
[docker-compose.txt](https://github.com/neon-lab-dev/login-service/files/14886965/docker-compose.txt)

# Note
before running the script uploaded, update the extention from `txt` to `yml`.

cc-  @smackdowna @PremanandChowdhury

**Comment by PremanandChowdhury** [comment]
Got it, working on it.
