### ISSUE TITLE
Documentation of the guideline and design

### ISSUE THREAD

**Issue by neon-lab-dev** [neon-lab-dev/login-service#2]
## Documentation
- Adding documentation to the project that acts as an guidelines to be followed while working on the project.
- General description to the repository based on the services it provides.
- Author of the documentation and details 
- Contributors in the same.

**Comment by ritik-agrawal** [comment]
Documentation and guidelines for login-service.

Link: https://docs.google.com/document/d/1paGi0ONDwZ1Z47QYiJvBxWryuKiI9v3sZk7sGqxMn7Y/edit?usp=sharing

Please request for access.
