### ISSUE TITLE
Bug fixes related to the login profile apis

### ISSUE THREAD

**Issue by neon-lab-dev** [neon-lab-dev/login-service#34]
# Problem

1. I am encountering  CORS error for the login service.
2. Additionally, we require user addresses when performing an admin fetch.
3. Furthermore, we need the total number of users in the database and the number of active users for statistics/reports.

![image](https://github.com/neon-lab-dev/login-service/assets/162788012/2cda6ea2-61db-4d6b-85d2-0a909e8e584b)

**Comment by ritik-agrawal** [comment]
All the requested changes have been done and tested.

cc- @smackdowna

**Comment by neon-lab-dev** [comment]
The above changes has been deployed and tested.
